spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_db
    username: postgres
    password: skffkfl28
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

# Server Configuration
server:
  port: 8082

# JWT Configuration (Custom properties)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 256-bit safe secret
  expiration: 3600000 # 1 hour (Access Token)
  refresh-expiration: 1209600000 # 14 days (Refresh Token)

# SpringDoc OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    path: /api/docs/jwt/openapi
  swagger-ui:
    path: /api/docs/jwt
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: JWT Authentication API
    description: Spring Boot JWT 인증 시스템 - Redis 블랙리스트와 Dual Token 정책을 활용한 보안 강화형 인증 API
    version: 1.0.0
